# Generated by Django 4.0 on 2021-12-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0002_dish_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='category', verbose_name='Изображение')),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='prise',
        ),
    ]
