# Generated by Django 4.0 on 2021-12-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coock', '0003_categorie_remove_dish_photo_remove_dish_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calorie',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coock.categorie'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dish', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='source',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='vote',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='UserDishRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.PositiveSmallIntegerField()),
                ('loved', models.BooleanField(default=False)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coock.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='dish', verbose_name='Изображение')),
                ('ingredients', models.PositiveSmallIntegerField(default=0)),
                ('steps', models.PositiveSmallIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coock.dish')),
            ],
        ),
    ]
