# Generated by Django 4.0 on 2021-12-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0005_alter_dish_calorie_alter_dish_source_alter_dish_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coock.categorie'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.TextField(),
        ),
    ]
