# Generated by Django 4.0 on 2021-12-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0006_alter_dish_category_alter_dish_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
