# Generated by Django 4.0 on 2021-12-24 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0007_alter_dish_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdishrelationship',
            name='Rating',
        ),
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='userdishrelationship',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='calorie',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coock.categorie'),
        ),
    ]
