# Generated by Django 4.0 on 2021-12-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0008_remove_userdishrelationship_rating_dish_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdishrelationship',
            old_name='rating',
            new_name='rate',
        ),
    ]
