# Generated by Django 4.0 on 2021-12-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0009_rename_rating_userdishrelationship_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdishrelationship',
            name='rate',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
