# Generated by Django 4.0 on 2021-12-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0012_alter_userdishrelationship_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdishrelationship',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
