# Generated by Django 4.0 on 2021-12-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('coock', '0014_alter_userdishrelationship_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdishrelationship',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userdishrelationship',
            unique_together={('user', 'dish')},
        ),
    ]
