# Generated by Django 4.0 on 2021-12-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0015_alter_userdishrelationship_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
