# Generated by Django 4.0 on 2021-12-24 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0016_preview_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdishrelationship',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coock.preview'),
        ),
    ]
