# Generated by Django 4.0 on 2022-01-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0018_author_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
