# Generated by Django 4.0 on 2022-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0020_testnames'),
    ]

    operations = [
        migrations.AddField(
            model_name='testnames',
            name='age',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='testnames',
            name='family',
            field=models.CharField(max_length=255, null=True, verbose_name='имя'),
        ),
    ]
