# Generated by Django 4.0 on 2022-02-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0021_testnames_age_testnames_family'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestNames',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='preview',
            name='image',
        ),
        migrations.AddField(
            model_name='categorie',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='category\\mobile', verbose_name='Image for mobile'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='web_image',
            field=models.ImageField(blank=True, upload_to='category\\web', verbose_name='Image for web'),
        ),
        migrations.AddField(
            model_name='dish',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='dish\\mobile', verbose_name='Image for mobile'),
        ),
        migrations.AddField(
            model_name='dish',
            name='web_image',
            field=models.ImageField(blank=True, upload_to='dish\\web', verbose_name='Image for web'),
        ),
        migrations.AddField(
            model_name='preview',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coock.categorie'),
        ),
        migrations.AddField(
            model_name='preview',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='preview\\mobile', verbose_name='Image for mobile'),
        ),
        migrations.AddField(
            model_name='preview',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='preview',
            name='web_image',
            field=models.ImageField(blank=True, upload_to='preview\\web', verbose_name='Image for web'),
        ),
    ]
