# Generated by Django 4.0 on 2022-03-30 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0022_delete_testnames_remove_categorie_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='dish\\web', verbose_name='Image for web')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coock.dish')),
            ],
        ),
    ]
