# Generated by Django 4.0 on 2022-03-30 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0023_steps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steps',
            new_name='Step',
        ),
    ]
