# Generated by Django 4.0 on 2022-03-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coock', '0024_rename_steps_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, upload_to='dish\\steps', verbose_name='Step illustration'),
        ),
    ]
